.DEFAULT_GOAL := all
.DELETE_ON_ERROR:

ifeq ($(filter -j% --jobs% --jobserver%,$(MAKEFLAGS)),)
BUILD_JOBS := $(shell nproc 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1)
MAKEFLAGS += -j$(BUILD_JOBS)
endif

CXX ?= g++
PKG_CONFIG ?= pkg-config
BUILD_DIR ?= build
CXXFLAGS ?= -O2 -DNDEBUG
RUN_ARGS ?=

QT_PACKAGES := Qt6Widgets Qt6Network libcrypto
QT_CFLAGS := $(shell $(PKG_CONFIG) --cflags $(QT_PACKAGES) 2>/dev/null)
QT_LIBS := $(shell $(PKG_CONFIG) --libs $(QT_PACKAGES) 2>/dev/null)
QT_LIBEXECDIR := $(shell $(PKG_CONFIG) --variable=libexecdir Qt6Core 2>/dev/null)
MOC ?= $(if $(QT_LIBEXECDIR),$(QT_LIBEXECDIR)/moc,moc)
RCC ?= $(if $(QT_LIBEXECDIR),$(QT_LIBEXECDIR)/rcc,rcc)

TARGET := $(BUILD_DIR)/YusiManager
ICON := $(BUILD_DIR)/yusimanager.png
SOURCES := $(wildcard src/*.cpp)
HEADERS := $(wildcard src/*.h)
MOC_HEADERS := src/mainwindow.h src/profiles_model.h src/filter_proxy.h src/group_header_proxy.h
MOC_SOURCES := $(patsubst src/%.h,$(BUILD_DIR)/moc_%.cpp,$(MOC_HEADERS))
RESOURCE_SOURCE := $(BUILD_DIR)/qrc_resources.cpp
OBJECTS := $(patsubst src/%.cpp,$(BUILD_DIR)/%.o,$(SOURCES)) \
           $(MOC_SOURCES:.cpp=.o) $(RESOURCE_SOURCE:.cpp=.o)
DEPS := $(OBJECTS:.o=.d)

.PHONY: all run clean help check-deps
.SECONDARY: $(MOC_SOURCES) $(RESOURCE_SOURCE)

all: $(TARGET) $(ICON)

check-deps:
	@command -v $(CXX) >/dev/null 2>&1 || { echo 'A C++20 compiler is required (for example g++).'; exit 1; }
	@command -v $(PKG_CONFIG) >/dev/null 2>&1 || { echo 'Install pkg-config (or pkgconf) and the Qt 6 base development packages; see README.md.'; exit 1; }
	@$(PKG_CONFIG) --exists $(QT_PACKAGES) || { echo 'Qt 6 Widgets/Network or OpenSSL development files are missing; see README.md.'; exit 1; }
	@command -v "$(MOC)" >/dev/null 2>&1 || { echo 'Qt 6 moc is missing; install the Qt 6 base development tools or set MOC=/path/to/moc.'; exit 1; }
	@command -v "$(RCC)" >/dev/null 2>&1 || { echo 'Qt 6 rcc is missing; install the Qt 6 base development tools or set RCC=/path/to/rcc.'; exit 1; }

$(BUILD_DIR):
	mkdir -p "$@"

$(TARGET): $(OBJECTS) Makefile | check-deps
	$(CXX) $(LDFLAGS) -o "$@" $(OBJECTS) $(LDLIBS) $(QT_LIBS)

$(BUILD_DIR)/%.o: src/%.cpp Makefile | check-deps $(BUILD_DIR)
	$(CXX) $(CPPFLAGS) $(QT_CFLAGS) -Isrc $(CXXFLAGS) -std=c++20 -fPIC -MMD -MP -c "$<" -o "$@"

$(BUILD_DIR)/moc_%.cpp: src/%.h $(HEADERS) Makefile | check-deps $(BUILD_DIR)
	"$(MOC)" $(CPPFLAGS) $(QT_CFLAGS) -Isrc "$<" -o "$@"

$(BUILD_DIR)/moc_%.o: $(BUILD_DIR)/moc_%.cpp Makefile | check-deps $(BUILD_DIR)
	$(CXX) $(CPPFLAGS) $(QT_CFLAGS) -Isrc $(CXXFLAGS) -std=c++20 -fPIC -MMD -MP -c "$<" -o "$@"

$(RESOURCE_SOURCE): src/resources.qrc src/yusimanager.png $(wildcard src/icons/*.png src/translations/*) Makefile | check-deps $(BUILD_DIR)
	"$(RCC)" --name resources "$<" -o "$@"

$(BUILD_DIR)/qrc_resources.o: $(RESOURCE_SOURCE) Makefile | check-deps $(BUILD_DIR)
	$(CXX) $(CPPFLAGS) $(QT_CFLAGS) -Isrc $(CXXFLAGS) -std=c++20 -fPIC -MMD -MP -c "$<" -o "$@"

$(ICON): src/yusimanager.png | $(BUILD_DIR)
	cp "$<" "$@"

run: all
	"$(TARGET)" $(RUN_ARGS)

clean:
	rm -f $(OBJECTS) $(DEPS) $(MOC_SOURCES) $(RESOURCE_SOURCE) "$(TARGET)" "$(ICON)"

help:
	@printf '%s\n' \
		'make              Compile using all available CPU cores' \
		'make -j4          Compile using four parallel jobs' \
		'make run          Compile and start YusiManager' \
		'make clean        Remove files generated by this Makefile' \
		'' \
		'Options: BUILD_DIR=build-debug CXX=clang++ CXXFLAGS="-O0 -g"' \
		'         MOC=/path/to/moc RCC=/path/to/rcc RUN_ARGS="--minimized"' \
		'After changing compiler flags, run make clean before rebuilding.'

-include $(DEPS)
